routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return redirect('dashboard');
//});

Route::group(['namespace'=>'Site'], function(){
    Route::get('/', 'WebsiteController@getIndex')->name('front_page');
    Route::get('about', 'WebsiteController@getAbout')->name('about');
    Route::get('contact', 'WebsiteController@getContact')->name('contact');
    Route::get('search', 'WebsiteController@getSearch')->name('search');

    Route::post('search/filter', 'WebsiteController@postSearchFilter')->name('search-filter');

    Route::get('login', function(){
        return redirect('dashboard');
    });
    Route::get('register', function(){
        return redirect('dashboard');
    });
});

Route::get('app-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth'], 'namespace' => 'Admin'], function (){
    Route::resource('dashboard', 'DashboardController');
    Route::resource('animal-class', 'AnimalClassController');
    Route::resource('subgroup', 'SubGroupController');
    Route::resource('species', 'SpeciesController');
    Route::resource('common-name', 'CommonNameController');
    Route::resource('tissue-type', 'TissueTypeController');
    Route::resource('cell-type', 'CellTypeController');
    Route::resource('notes', 'NoteController');
    Route::resource('aliquot', 'AliquetController');
    Route::resource('cell-line', 'CellLineController');
    Route::resource('publication', 'PublicationController');

    Route::get('profile', 'UserController@getProfile')->name('profile');
    Route::post('change-password', 'UserController@postChangePass')->name('change-password');
    Route::get('logout', 'DashboardController@logout');

    Route::get('enquiry', 'EnquiryController@index');
});

app/Aliquet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Aliquet extends Model
{
    protected $fillable = ['passenger_number', 'cryopreservation_date', 'status'];
    protected $hidden = ['created_at', 'updated_at', 'deleted_at'];
}

app/Http/Controllers/Admin/AliquetController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Aliquet;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AliquetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.aliquet.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.aliquet.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $aliquet = new Aliquet();
        $aliquet->passenger_number = $request->get('passenger_number');
        $aliquet->cryopreservation_date = $request->get('cryopreservation_date', Carbon::now()->format('Y-m-d'));
        $aliquet->status = $request->get('status', 1);
        $aliquet->save();

        $request->session()->put('aliquet_create', true);
        return redirect(route('aliquet.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return redirect(route('aliquet.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $aliquet = Aliquet::where('id', $id)->first();
        if ($aliquet == null){
            return redirect(route('aliquet.index'));
        }

        return view('admin.aliquet.form', compact('aliquet'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $aliquet = Aliquet::where('id', $id)->first();
        if ($aliquet == null){
            return redirect(route('aliquet.index'));
        }

        $aliquet->passenger_number = $request->get('passenger_number');
        $aliquet->cryopreservation_date = $request->get('cryopreservation_date', Carbon::now()->format('Y-m-d'));
        $aliquet->status = $request->get('status', 1);
        $aliquet->save();

        $request->session()->put('aliquet_update', true);
        return redirect(route('aliquet.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/aliquet/form.blade.php
@extends('layouts.admin-panel')

@section('title', 'Aliquots')

@section('page_styles')
    <link rel="stylesheet" href="{{ asset('css/plugins/datapicker/datepicker3.css') }}" />
    <link rel="stylesheet" href="{{ asset('css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css') }}" />
@endsection

@section('page_scripts')
    <script src="{{ asset('js/plugins/datapicker/bootstrap-datepicker.js') }}"></script>
    <script src="{{ asset('js/plugins/iCheck/icheck.min.js') }}"></script>
    <script>

        $('.date-control').datepicker({
            todayBtn: false,
            todayHighlight: true,
            format: 'yyyy-mm-dd'
        });
        $('#frm').validate({
            rules: {
                passenger_number: {
                    required: true,
                    number: true
                },
                cryopreservation_date: "required"
            }
        });
    </script>
@endsection

@section('page_header')
    <h1>Aliquots</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="breadcrumb-item active"><a href="{{ route('aliquot.index') }}">Aliquots</a></li>
        <li class="breadcrumb-item active"><strong>{{ isset($aliquet) ? "Edit Aliquots" : "Create Aliquots" }}</strong></li>
    </ol>
@endsection

@section('page_content')
    <div class="row">
        <div class="col-md-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>{{ isset($aliquet) ? "Edit Aliquots" : "Create Aliquots" }}</h5>
                    <div class="ibox-tools">
                        <a href="{{ route('aliquot.index') }}">
                            <i class="fa fa-long-arrow-left"></i>
                        </a>
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" id="frm" action="{{ isset($aliquet) ? route('aliquot.update', $aliquet->id) : route('aliquot.store') }}" method="post">
                        @csrf
                        @if (isset($aliquet))
                            {{ method_field('PUT') }}
                            <input type="hidden" name="id" value="{{ $aliquet->id }}" />
                        @endif
                        <div class="row form-group">
                            <label for="" class="col-md-3 col-form-label">Passenger Number: </label>
                            <div class="col-md-9">
                                <input type="text" name="passenger_number" id="passenger_number" class="form-control" value="{{ isset($aliquet) ? $aliquet->passenger_number : "" }}" />
                            </div>
                        </div>
                        <div class="row form-group">
                            <label for="" class="col-md-3 col-form-label">Cryopreservation Date: </label>
                            <div class="col-md-9">
                                <input type="text" name="cryopreservation_date" id="cryopreservation_date" class="form-control date-control" readonly value="{{ isset($aliquet) ? substr($aliquet->cryopreservation_date, 0, 10): "" }}" />
                            </div>
                        </div>
                        <div class="row form-group">
                            <label for="" class="col-md-3 col-form-label">Status: </label>
                            <div class="col-md-9">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="radio radio-primary">
                                            <input type="radio" name="status" id="status_1" value="1" {{ ( isset($aliquet) && $aliquet->status == 1 ) ? 'checked' : ( (!isset($aliquet)) ? 'checked' : '' ) }} />
                                            <label for="status_1">In Stock</label>
                                        </div>
                                    </div>
                                    <div class="col-md-4 radio radio-danger">
                                        <div class="radio radio-danger">
                                            <input type="radio" name="status" id="status_2" value="2" {{ ( isset($aliquet) && $aliquet->status == 2 ) ? 'checked' : ''  }} />
                                            <label for="status_2">Out of Stock</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="row form-group">
                            <div class="col-md-12 text-right">
                                <button class="btn btn-primary btn-sm" type="submit">{{ isset($aliquet) ? "Update" : "Save" }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/aliquet/index.blade.php
@extends('layouts.admin-panel')

@section('title', 'Aliquots')

@section('page_styles')
@endsection

@section('page_scripts')
    <script>
        $('#tblAliquet').dataTable({
            processing: true,
            serverSide: true,
            cache: false,
            ajax: {
                url: '{{ url('data/aliquet') }}',
                type: "POST",
                dataSrc: "data",
                data: {
                    _token: '{{ csrf_token() }}'
                }
            },
            columns: [
                { data: "id", searchable: false, sortable: false, visible: false },
                { data: "passenger_number" },
                { data: "cryopreservation_date" },
                { data: "status" },
                { data: "cellLineCount", className: "text-right" },
                { data: 'action', searchable: false, sortable: false, className: 'text-right' }
            ]
        });
    </script>
@endsection

@section('page_header')
    <h1>Aliquots</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="breadcrumb-item active"><strong>Aliquots</strong></li>
    </ol>
@endsection

@section('page_content')
    @if (Session::has('aliquet_create'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success alert-dismissable">
                    <strong>Success...</strong>
                    Aliquots inserted successfully...
                    <button data-dismiss="alert" class="close">&times;</button>
                </div>
            </div>
        </div>
        @php Session::forget('aliquet_create') @endphp
    @endif
    @if (Session::has('aliquet_update'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success alert-dismissable">
                    <strong>Success...</strong>
                    Aliquots updated successfully...
                    <button data-dismiss="alert" class="close">&times;</button>
                </div>
            </div>
        </div>
        @php Session::forget('aliquet_update') @endphp
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Aliquets</h5>
                    <div class="ibox-tools">
                        <a href="{{ route('aliquot.create') }}">
                            <i class="fa fa-plus"></i>
                        </a>
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-striped table-bordered" id="tblAliquet">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Passenger Numbers</th>
                                        <th>Cryopreservation Date</th>
                                        <th>Status</th>
                                        <th>Cell Lines</th>
                                        <th></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection