routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return redirect('dashboard');
//});

Route::group(['namespace'=>'Site'], function(){
    Route::get('/', 'WebsiteController@getIndex')->name('front_page');
    Route::get('about', 'WebsiteController@getAbout')->name('about');
    Route::get('contact', 'WebsiteController@getContact')->name('contact');
    Route::get('search', 'WebsiteController@getSearch')->name('search');

    Route::post('search/filter', 'WebsiteController@postSearchFilter')->name('search-filter');

    Route::get('login', function(){
        return redirect('dashboard');
    });
    Route::get('register', function(){
        return redirect('dashboard');
    });
});

Route::get('app-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth'], 'namespace' => 'Admin'], function (){
    Route::resource('dashboard', 'DashboardController');
    Route::resource('animal-class', 'AnimalClassController');
    Route::resource('subgroup', 'SubGroupController');
    Route::resource('species', 'SpeciesController');
    Route::resource('common-name', 'CommonNameController');
    Route::resource('tissue-type', 'TissueTypeController');
    Route::resource('cell-type', 'CellTypeController');
    Route::resource('notes', 'NoteController');
    Route::resource('aliquot', 'AliquetController');
    Route::resource('cell-line', 'CellLineController');
    Route::resource('publication', 'PublicationController');

    Route::get('profile', 'UserController@getProfile')->name('profile');
    Route::post('change-password', 'UserController@postChangePass')->name('change-password');
    Route::get('logout', 'DashboardController@logout');

    Route::get('enquiry', 'EnquiryController@index');
});

app/Http/Controllers/Admin/CellTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\CellType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CellTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.cell-type.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.cell-type.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $type = $request->get('type');
        $cellType = new CellType();

        $cellType->type = $type;
        $cellType->save();

        $request->session()->put('celltype_create', true);
        return redirect(route('cell-type.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return redirect(route('cell-type.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $cellType = CellType::where('id', $id)->first();
        if ($cellType == null){
            return redirect(route('cell-type.index'));
        }

        return view('admin.cell-type.form', compact(
            'cellType'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $cellType = CellType::where('id', $id)->first();
        if ($cellType == null){
            return redirect(route('cell-type.index'));
        }

        $cellType->type = $request->get('type');
        $cellType->save();

        $request->session()->put('celltype_update', true);
        return redirect(route('cell-type.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/cell-type/form.blade.php
@extends('layouts.admin-panel')

@section('title', 'Cell Types')

@section('page_styles')
@endsection

@section('page_scripts')
    <script>
        $('#frm').validate({
            rules: {
                type: "required"
            }
        });
    </script>
@endsection

@section('page_header')
    <h1>Cell Types</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="breadcrumb-item active"><a href="{{ route('cell-type.index') }}">Cell Types</a></li>
        <li class="breadcrumb-item active"><strong>{{ isset($cellType) ? "Edit Cell Type" : "Create Cell Type" }}</strong></li>
    </ol>
@endsection

@section('page_content')
    <div class="row">
        <div class="col-md-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>{{ isset($cellType) ? "Edit Cell Type" : "Create Cell Type" }}</h5>
                    <div class="ibox-tools">
                        <a href="{{ route('cell-type.index') }}">
                            <i class="fa fa-long-arrow-left"></i>
                        </a>
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" id="frm" action="{{ isset($cellType) ? route('cell-type.update', $cellType->id) : route('cell-type.store') }}" method="post">
                        @csrf
                        @if (isset($cellType))
                            {{ method_field('PUT') }}
                            <input type="hidden" name="id" value="{{ $cellType->id }}" />
                        @endif
                        <div class="row form-group">
                            <label for="" class="col-md-3 col-form-label">Type: </label>
                            <div class="col-md-9">
                                <input type="text" name="type" id="type" class="form-control" value="{{ isset($cellType) ? $cellType->type : "" }}" />
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="row form-group">
                            <div class="col-md-12 text-right">
                                <button class="btn btn-primary btn-sm" type="submit">{{ isset($cellType) ? "Update" : "Save" }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/cell-type/index.blade.php
@extends('layouts.admin-panel')

@section('title', 'Cell Types')

@section('page_styles')
@endsection

@section('page_scripts')
    <script>
        $('#tblCellType').dataTable({
            processing: true,
            serverSide: true,
            cache: false,
            ajax: {
                url: '{{ url('data/cell-type') }}',
                type: "POST",
                dataSrc: "data",
                data: {
                    _token: '{{ csrf_token() }}'
                }
            },
            columns: [
                { data: "id", searchable: false, sortable: false, visible: false },
                { data: "type" },
                { data: "cellLineCount", className: "text-right" },
                { data: 'action', searchable: false, sortable: false, className: "text-right" }
            ]
        });
    </script>
@endsection

@section('page_header')
    <h1>Cell Types</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="breadcrumb-item active"><strong>Cell Types</strong></li>
    </ol>
@endsection

@section('page_content')
    @if (Session::has('celltype_create'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success alert-dismissable">
                    <strong>Success...</strong>
                    Cell Type inserted successfully...
                    <button data-dismiss="alert" class="close">&times;</button>
                </div>
            </div>
        </div>
        @php Session::forget('celltype_create') @endphp
    @endif
    @if (Session::has('celltype_update'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success alert-dismissable">
                    <strong>Success...</strong>
                    Cell Type updated successfully...
                    <button data-dismiss="alert" class="close">&times;</button>
                </div>
            </div>
        </div>
        @php Session::forget('celltype_update') @endphp
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Cell Types</h5>
                    <div class="ibox-tools">
                        <a href="{{ route('cell-type.create') }}">
                            <i class="fa fa-plus"></i>
                        </a>
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-striped table-bordered" id="tblCellType">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Type</th>
                                        <th>Cell Lines</th>
                                        <th></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection