routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return redirect('dashboard');
//});

Route::group(['namespace'=>'Site'], function(){
    Route::get('/', 'WebsiteController@getIndex')->name('front_page');
    Route::get('about', 'WebsiteController@getAbout')->name('about');
    Route::get('contact', 'WebsiteController@getContact')->name('contact');
    Route::get('search', 'WebsiteController@getSearch')->name('search');

    Route::post('search/filter', 'WebsiteController@postSearchFilter')->name('search-filter');

    Route::get('login', function(){
        return redirect('dashboard');
    });
    Route::get('register', function(){
        return redirect('dashboard');
    });
});

Route::get('app-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth'], 'namespace' => 'Admin'], function (){
    Route::resource('dashboard', 'DashboardController');
    Route::resource('animal-class', 'AnimalClassController');
    Route::resource('subgroup', 'SubGroupController');
    Route::resource('species', 'SpeciesController');
    Route::resource('common-name', 'CommonNameController');
    Route::resource('tissue-type', 'TissueTypeController');
    Route::resource('cell-type', 'CellTypeController');
    Route::resource('notes', 'NoteController');
    Route::resource('aliquot', 'AliquetController');
    Route::resource('cell-line', 'CellLineController');
    Route::resource('publication', 'PublicationController');

    Route::get('profile', 'UserController@getProfile')->name('profile');
    Route::post('change-password', 'UserController@postChangePass')->name('change-password');
    Route::get('logout', 'DashboardController@logout');

    Route::get('enquiry', 'EnquiryController@index');
});

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $fillable = [ 'title', 'link' ];
    protected  $hidden = [ 'created_at', 'updated_at', 'deleted_at' ];
}

app/Http/Controllers/Admin/NoteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Note;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class NoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.note.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.note.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $title = $request->get('title');
        $link = $request->get('link');
        $note = new Note();

        $note->title = $title;
        $note->link = $link;
        $note->save();

        $request->session()->put('note_create', true);
        return redirect(route('notes.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return redirect(route('notes.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $note = Note::where('id', $id)->first();
        if ($note == null){
            return redirect(route('notes.index'));
        }

        return view('admin.note.form', compact(
            'note'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $note = Note::where('id', $id)->first();
        if ($note == null){
            return redirect(route('notes.index'));
        }

        $note->title = $request->get('title');
        $note->link = $request->get('link');
        $note->save();

        $request->session()->put('note_update', true);
        return redirect(route('notes.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/note/form.blade.php
@extends('layouts.admin-panel')

@section('title', 'Notes')

@section('page_styles')
@endsection

@section('page_scripts')
    <script>
        $('#frm').validate({
            rules: {
                title: "required",
                link: {
                    "required": true,
                }
            }
        });
    </script>
@endsection

@section('page_header')
    <h1>Notes</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="breadcrumb-item active"><a href="{{ route('notes.index') }}">Notes</a></li>
        <li class="breadcrumb-item active"><strong>{{ isset($note) ? "Edit Note" : "Create Note" }}</strong></li>
    </ol>
@endsection

@section('page_content')
    <div class="row">
        <div class="col-md-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>{{ isset($note) ? "Edit Note" : "Create Note" }}</h5>
                    <div class="ibox-tools">
                        <a href="{{ route('notes.index') }}">
                            <i class="fa fa-long-arrow-left"></i>
                        </a>
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" id="frm" action="{{ isset($note) ? route('notes.update', $note->id) : route('notes.store') }}" method="post">
                        @csrf
                        @if (isset($note))
                            {{ method_field('PUT') }}
                            <input type="hidden" name="id" value="{{ $note->id }}" />
                        @endif
                        <div class="row form-group">
                            <label for="" class="col-md-3 col-form-label">Title: </label>
                            <div class="col-md-9">
                                <input type="text" name="title" id="title" class="form-control" value="{{ isset($note) ? $note->title : "" }}" />
                            </div>
                        </div>
                        <div class="row form-group">
                            <label for="" class="col-md-3 col-form-label">Link: </label>
                            <div class="col-md-9">
                                <input type="text" name="link" id="link" class="form-control" value="{{ isset($note) ? $note->link : "" }}" />
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="row form-group">
                            <div class="col-md-12 text-right">
                                <button class="btn btn-primary btn-sm" type="submit">{{ isset($note) ? "Update" : "Save" }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/note/index.blade.php
@extends('layouts.admin-panel')

@section('title', 'Notes')

@section('page_styles')
@endsection

@section('page_scripts')
    <script>
        $('#tblNotes').dataTable({
            processing: true,
            serverSide: true,
            cache: false,
            ajax: {
                url: '{{ url('data/note') }}',
                type: "POST",
                dataSrc: "data",
                data: {
                    _token: '{{ csrf_token() }}'
                }
            },
            columns: [
                { data: "id", searchable: false, sortable: false, visible: false },
                { data: "title" },
                { data: "link" },
                { data: "cellLineCount", className: "text-right" },
                { data: 'action', searchable: false, sortable: false, className: "text-right" }
            ]
        });
    </script>
@endsection

@section('page_header')
    <h1>Notes</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="breadcrumb-item active"><strong>Notes</strong></li>
    </ol>
@endsection

@section('page_content')
    @if (Session::has('note_create'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success alert-dismissable">
                    <strong>Success...</strong>
                    Note inserted successfully...
                    <button data-dismiss="alert" class="close">&times;</button>
                </div>
            </div>
        </div>
        @php Session::forget('note_create') @endphp
    @endif
    @if (Session::has('note_update'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success alert-dismissable">
                    <strong>Success...</strong>
                    Note updated successfully...
                    <button data-dismiss="alert" class="close">&times;</button>
                </div>
            </div>
        </div>
        @php Session::forget('note_update') @endphp
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Notes</h5>
                    <div class="ibox-tools">
                        <a href="{{ route('notes.create') }}">
                            <i class="fa fa-plus"></i>
                        </a>
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-striped table-bordered" id="tblNotes">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Link</th>
                                        <th>Cell Lines</th>
                                        <th></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection